apiVersion: v1
kind: ConfigMap
metadata:
  name: html-configmap
data:
  index.html: |-
    <h1>Hola mundo desde un configMap</h1>
    <h2>Hola mundo desde un configMap</h2>
    <ul>
      <li>
        Hola mundo desde un configMap
      </li>
    </ul>

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-volumen-configmap
  labels:
    name: nginx-volumen-configmap
spec:
  containers:
  - name: nginx-volumen-configmap
    image: nginx
    volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: index-html
    resources:
      limits:
        memory: "64Mi"
        cpu: "250m"
    ports:
      - containerPort: 80
  volumes:
  - name: index-html
    configMap:
      name: html-configmap
      items:
        - key: index.html
          path: index.html