apiVersion: v1
kind: Pod
metadata:
  name: nginx-volumen-hostpath
  labels:
    name: nginx-volumen-hostpath
spec:
  containers:
  - name: nginx-volumen-hostpath
    image: nginx
    volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: html-volume
    resources:
      limits:
        memory: "64Mi"
        cpu: "250m"
    ports:
      - containerPort: 80
  volumes:
  - name: html-volume
    hostPath:
      path: /var/www/
      type: Directory