apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim-cloud
spec:
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi